# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 16:24
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name=b'\xe7\xb1\xbb\xe5\x88\xab\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('num_of_view', models.IntegerField(default=0, verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe9\x87\x8f')),
                ('num_of_com', models.IntegerField(default=0, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0')),
                ('num_of_like', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe8\xb5\x9e\xe6\x95\xb0')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9 ')),
                ('image', models.ImageField(blank=True, default=b'static/image/Art_Image.jpg', upload_to=b'static/image/article_image/%Y/%m/%d', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xa5\xe6\x9c\x9f')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('com_text', models.CharField(max_length=200, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe5\x86\x85\xe5\xae\xb9')),
                ('num_of_com', models.IntegerField(default=0, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0')),
            ],
        ),
        migrations.CreateModel(
            name='LikeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('like_num', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True, verbose_name=b'\xe7\x99\xbb\xe5\xbd\x95\xe5\x90\x8d')),
                ('password', models.CharField(max_length=60, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xa5\xe6\x9c\x9f')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nickname', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\x9c\x9f\xe5\xae\x9e\xe5\xa7\x93\xe5\x90\x8d')),
                ('b_day', models.DateField(blank=True, null=True, verbose_name=b'\xe5\x87\xba\xe7\x94\x9f\xe6\x97\xa5\xe6\x9c\x9f')),
                ('gender', models.BooleanField(choices=[(0, '\u7537'), (1, '\u5973')], max_length=2, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('image', models.ImageField(blank=True, default=b'static/image/image.jpg', upload_to=b'static/image/user_logo/%Y/%m/%d', verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe5\x9c\xb0\xe5\x9d\x80')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xa5\xe6\x9c\x9f')),
                ('username', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Article')),
                ('read_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommentArt',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblogapp.Comment')),
            ],
            bases=('myblogapp.comment',),
        ),
        migrations.CreateModel(
            name='CommentCom',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblogapp.Comment')),
                ('com_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.CommentArt')),
            ],
            bases=('myblogapp.comment',),
        ),
        migrations.AddField(
            model_name='likerecord',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myblogapp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.ArtCategory'),
        ),
        migrations.AddField(
            model_name='commentart',
            name='com_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Article'),
        ),
    ]
