# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 15:18
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='introduction',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name=b'\xe7\xae\x80\xe4\xbb\x8b'),
        ),
    ]
