# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('num_of_com', models.IntegerField(default=0, verbose_name='评论数')),
                ('num_of_like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('content', models.TextField(max_length=10000, verbose_name='内容')),
                ('image', models.ImageField(blank=True, default='./static/image/Art_Image.jpg', upload_to='', verbose_name='图片')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 4, 8, 21, 2, 16, 174963), verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('com_text', models.CharField(max_length=200, verbose_name='评论内容')),
                ('num_of_com', models.IntegerField(default=0, verbose_name='评论数')),
                ('num_of_like', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='密码最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nickname', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='昵称')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='真实姓名')),
                ('b_day', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.BooleanField(choices=[(0, '男'), (1, '女')], max_length=2, verbose_name='性别')),
                ('image', models.ImageField(blank=True, default='./static/image/image.jpg', null=True, upload_to='./static/image/', verbose_name='头像')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='电话')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('friends', models.ManyToManyField(to='myblogapp.UserInfo', verbose_name='朋友')),
                ('username', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommentArt',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblogapp.Comment')),
            ],
            bases=('myblogapp.comment',),
        ),
        migrations.CreateModel(
            name='CommentCom',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblogapp.Comment')),
                ('com_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.CommentArt')),
            ],
            bases=('myblogapp.comment',),
        ),
        migrations.CreateModel(
            name='LikeArt',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblogapp.Like')),
            ],
            bases=('myblogapp.like',),
        ),
        migrations.CreateModel(
            name='LikeCom',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblogapp.Like')),
            ],
            bases=('myblogapp.like',),
        ),
        migrations.AddField(
            model_name='like',
            name='like_person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.ArtCategory'),
        ),
        migrations.AddField(
            model_name='likecom',
            name='like_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Comment'),
        ),
        migrations.AddField(
            model_name='likeart',
            name='like_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Article'),
        ),
        migrations.AddField(
            model_name='commentart',
            name='com_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Article'),
        ),
    ]
