# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 21, 7, 37, 121573), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='myblogapp.UserInfo', verbose_name='朋友'),
        ),
    ]
