# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0002_auto_20190319_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=b'image/Art_Image.jpg', upload_to=b'image/article_image/%Y/%m/%d', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default=b'image/image.jpg', null=True, upload_to=b'image/user_logo/%Y/%m/%d', verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f'),
        ),
    ]
